import { Component } from '@angular/core';
import { TopNavbarComponent } from "../top-navbar/top-navbar.component";
import { FooterComponent } from "../footer/footer.component";
import { AccordionModule } from 'primeng/accordion';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-advice-usage',
  standalone: true,
  imports: [
    TopNavbarComponent,
    FooterComponent,
    CommonModule,
    RouterLink,
    AccordionModule,
  ],
  templateUrl: './advice-usage.component.html',
  styleUrl: './advice-usage.component.css'
})
export class AdviceUsageComponent {
    tabs = [
        { title: 'what is cybernorb?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'I need subscription for use it?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'How develope cybernorb website?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'Who should use cybernorb?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'How to make a post?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'How to share a single post?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'How to upload the video/image post?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
        { title: 'who develop the cybernorb?', content: 'Lorem adipisicing elit. Nostrum odit itaque dignissimos illum blanditiis nemocorporis soluta, fugit mollitia atque voluptatum accusantium. Aliasincidunt eligendi similique optio, veritatis animi sit illo mollitia rerumdolorum, at eius, beatae iste asperiores sunt omnis inventoreexercitationem? Nihil aut rerum illo accusamus explicabo maiores autemitaque perferendis quasi suscipit, eveniet iusto delectus esse culpa      placeat cum mollitia ab commodi voluptatem dolor iste incidunt minimanulla. Harum sunt vel pariatur architecto iure molestiae qui distinctiocum quibusdam officiis nostrum voluptates dignissimos accusantium adipisciodio praesentium quod beatae laborum fugiat, possimus numquam, repellendus deleniti? Fugiat iste ea sunt est! Odio necessitatibus at quidem officia milique molestias non ullam reprehenderitomnis' },
    
      ];

}
